version: "3"

services:
  mc_message_container:
    container_name: mc_rcon_messager
    build: .
    volumes:
        - "./app:/app"
        # path of minecraft server data directory(s)
    command: "python3 /app/main.py --msg ${MSG}"
