version: "3"
services:
  terraria_ps_control_app:
    container_name: terraria_psca
    image: mcr.microsoft.com/powershell:7.3-debian-bullseye-slim
    environment:
      TZ: "Europe/London"
    volumes:
      - ./app:/media
    secrets:
      - apitokens
    command: pwsh /media/scripts/${PSF}.ps1 ${ENDPOINT} ${MSG}

secrets:
  apitokens:
    file: tokens.json
